stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "=====test====="

docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build . -t $CI_REGISTRY_USER/gitlab-test
      #    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      #- docker push $CI_REGISTRY_USER/gitlab-test:$CI_COMMIT_SHA
      #- docker push $CI_REGISTRY_USER/gitlab-test:latest
