apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-test-deployment
  namespace: gitlab-test
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: lalll5555/gitlab-test:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-test-service
  namespace: apache
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache
  type: NodePort
